Makefiles rationalised
I bit the bullet and rationalised
the Makefiles a bit. No change to
system functionality.

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -1,27 +1,25 @@
 # Header include directory
 INCLDIR=$(TOP_SRCDIR)/include
 
-# Cross-compiling (e.g., on Mac OS X)
-# TOOLPREFIX = i386-jos-elf
-
 # Using native tools (e.g., on X86 Linux)
 #TOOLPREFIX = 
 
 # Try to infer the correct TOOLPREFIX if not set
 ifndef TOOLPREFIX
 TOOLPREFIX := $(shell if i386-jos-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
-	then echo 'i386-jos-elf-'; \
-	elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
-	then echo ''; \
-	else echo "***" 1>&2; \
-	echo "*** Error: Couldn't find an i386-*-elf version of GCC/binutils." 1>&2; \
-	echo "*** Is the directory with i386-jos-elf-gcc in your PATH?" 1>&2; \
-	echo "*** If your i386-*-elf toolchain is installed with a command" 1>&2; \
-	echo "*** prefix other than 'i386-jos-elf-', set your TOOLPREFIX" 1>&2; \
-	echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
-	echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
-	echo "***" 1>&2; exit 1; fi)
+        then echo 'i386-jos-elf-'; \
+        elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
+        then echo ''; \
+        else echo "***" 1>&2; \
+        echo "*** Error: Couldn't find an i386-*-elf version of GCC/binutils." 1>&2; \
+        echo "*** Is the directory with i386-jos-elf-gcc in your PATH?" 1>&2; \
+        echo "*** If your i386-*-elf toolchain is installed with a command" 1>&2; \
+        echo "*** prefix other than 'i386-jos-elf-', set your TOOLPREFIX" 1>&2; \
+        echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
+        echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
+        echo "***" 1>&2; exit 1; fi)
 endif
+
 
 # If the makefile can't find QEMU, specify its path here
 # QEMU = qemu-system-i386
@@ -29,17 +27,17 @@ endif
 # Try to infer the correct QEMU
 ifndef QEMU
 QEMU = $(shell if which qemu > /dev/null; \
-	then echo qemu; exit; \
-	elif which qemu-system-i386 > /dev/null; \
-	then echo qemu-system-i386; exit; \
-	else \
-	qemu=/Applications/Q.app/Contents/MacOS/i386-softmmu.app/Contents/MacOS/i386-softmmu; \
-	if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
-	echo "***" 1>&2; \
-	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
-	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
-	echo "*** or have you tried setting the QEMU variable in Makefile?" 1>&2; \
-	echo "***" 1>&2; exit 1)
+        then echo qemu; exit; \
+        elif which qemu-system-i386 > /dev/null; \
+        then echo qemu-system-i386; exit; \
+        else \
+        qemu=/Applications/Q.app/Contents/MacOS/i386-softmmu.app/Contents/MacOS/i386-softmmu; \
+        if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
+        echo "***" 1>&2; \
+        echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
+        echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
+        echo "*** or have you tried setting the QEMU variable in Makefile?" 1>&2; \
+        echo "***" 1>&2; exit 1)
 endif
 
 CC = $(TOOLPREFIX)gcc
@@ -49,9 +47,7 @@ RANLIB = $(TOOLPREFIX)ranlib
 LD = $(TOOLPREFIX)ld
 OBJCOPY = $(TOOLPREFIX)objcopy
 OBJDUMP = $(TOOLPREFIX)objdump
-#CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -O2 -Wall -MD -ggdb -m32 -Werror -fno-omit-frame-pointer
-CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -fvar-tracking -fvar-tracking-assignments -O0 -g -Wall -MD -gdwarf-2 -m32 -Werror -fno-omit-frame-pointer -nostdinc -I$(INCLDIR)
+CFLAGS = -fno-builtin -Wall -m32 -Werror -nostdinc -I$(INCLDIR)
 CFLAGS += $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
+LDFLAGS = -m $(shell $(LD) -V | grep elf_i386 2>/dev/null)
 ASFLAGS = -m32 -gdwarf-2 -Wa,-divide -nostdinc -I$(INCLDIR)
-# FreeBSD ld wants ``elf_i386_fbsd''
-LDFLAGS += -m $(shell $(LD) -V | grep elf_i386 2>/dev/null)
